### ISSUE TITLE
无法进行安装插件中的详细设置

### ISSUE THREAD

**Issue by PftHost** [tension/QQConnent-For-WHMCS#1]
在模块插件中，启用，配置，并赋予了权限，但在插件安装中，无法打开QQ Connect进行详细设置，访问出现白屏，请问这可能是什么原因？
WHMCS版本是7.0.1，Lamp环境，php5.6.30

**Comment by tension** [comment]
实在抱歉，开源产品不提供任何的技术支持。

如需技术支持可以购买我们的产品，可获得终身技术支持。
